//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.myServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="myServices.IMathInterface")]
    public interface IMathInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathInterface/AddFunc", ReplyAction="http://tempuri.org/IMathInterface/AddFuncResponse")]
        double AddFunc(double first, double second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathInterface/AddFunc", ReplyAction="http://tempuri.org/IMathInterface/AddFuncResponse")]
        System.Threading.Tasks.Task<double> AddFuncAsync(double first, double second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathInterface/SubFunc", ReplyAction="http://tempuri.org/IMathInterface/SubFuncResponse")]
        double SubFunc(double first, double second);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathInterface/SubFunc", ReplyAction="http://tempuri.org/IMathInterface/SubFuncResponse")]
        System.Threading.Tasks.Task<double> SubFuncAsync(double first, double second);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathInterfaceChannel : WcfClient.myServices.IMathInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathInterfaceClient : System.ServiceModel.ClientBase<WcfClient.myServices.IMathInterface>, WcfClient.myServices.IMathInterface {
        
        public MathInterfaceClient() {
        }
        
        public MathInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double AddFunc(double first, double second) {
            return base.Channel.AddFunc(first, second);
        }
        
        public System.Threading.Tasks.Task<double> AddFuncAsync(double first, double second) {
            return base.Channel.AddFuncAsync(first, second);
        }
        
        public double SubFunc(double first, double second) {
            return base.Channel.SubFunc(first, second);
        }
        
        public System.Threading.Tasks.Task<double> SubFuncAsync(double first, double second) {
            return base.Channel.SubFuncAsync(first, second);
        }
    }
}
